---
title: "iteration and listcols"
author: "Yingyu Cui"
date: "2024-11-3"
output: github_document
---

```{r set up}
library(tidyverse)
library(rvest)

set.seed(1)
```

an example about lists
```{r list example}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l

# I could pull some elements out of the list
l$vec_numeric
l[[3]]  # means the nth element of the list
l[["vec_numeric"]]  # the same as l$vec_numeric
l[["vec_numeric"]][1:3]
mean(l[["vec_numeric"]])

# the number of items in each list element could be different
```

# for loop
create a new list
```{r for loop new list}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

apply the function we have created before
```{r for loop function creation}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```
create a for loop
```{r for loop}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

# map in purrr
```{r map}
output = map(list_norms, mean_and_sd)
output1 = map(list_norms, median)
# which could apply any standard function to the list
```

#  if you know what kind of output you’re going to produce
```{r map_dbl}
output2 = map_dbl(list_norms, median, .id = "input")
# we could transfer the output to a vector if they are all double variables
```
```{r data frame}
output3 = map_dfr(list_norms, mean_and_sd, .id = "input")
# id = will add a column to the output, which says the name of the list elements
#also, might be useful in a pipe chain
```

```{r map2}
output = map2(input_1, input_2, \(x,y) func(arg_1 = x, arg_2 = y))
# which could use some function with two arguments like x + y, which could input_1 + input_2
```

# list columns 
```{r list columns}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df |> pull(name)
listcol_df |> pull(samp)
# here we are talking about list as a column

listcol_df$samp[[1]]
# we could pull some elements in a list as what we did before

mean_and_sd(listcol_df$samp[[1]])

map(listcol_df$samp, mean_and_sd)

# store the results as a new column
listcol_df = 
  listcol_df |> 
  mutate(summary = map(samp, mean_and_sd))

listcol_df


```

# application
```{r application}
nsduh_table <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
}
```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

output = vector("list", 3)

for (i in c(1, 4, 5)) {
  output[[i]] = nsduh_table(nsduh_html, i)
}

nsduh_results = bind_rows(output)
```

```{r}
nsduh_results = 
  map(c(1, 4, 5), nsduh_table, html = nsduh_html) |> 
  bind_rows()
```

# nest data 
```{r rnoaa data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


```{r nest data}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest
# we find what is the constant column and what is the list column, nest means we put other things into a list column

weather_nest |> pull(data)

unnest(weather_nest, cols = data)
```

# write a function
```{r function}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
```

```{r}
weather_lm(weather_nest$data[[1]])
map(weather_nest$data, weather_lm)

map(weather_nest$data, \(df) lm(tmax ~ tmin, data = df))
# \(df) is a lambda function, which is the same as function(df), which could simplify the step of writing a function
# but you could still write a function if you want

```

```{r}
weather_nest = 
  weather_nest |> 
  mutate(models = map(data, weather_lm))

weather_nest
#  keep track of models across stations, and to perform additional analyses.
```

# for data importing
```{r data importing}
full_df = 
  tibble(
    files = list.files("data/exp_data/"),
    path = str_c("data/exp_data/", files)
  ) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest()

# we could use this to import multiple files
# unnest to make the data frame
```


